name: navy
description: "A Flutter Social App"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animate_do: ^3.3.4
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.16
  get: ^4.6.6
  google_fonts: ^6.2.1

  #Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2

  #notifications:
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1

  #networking
  # http: ^1.2.2
  http_parser: ^4.0.0
  dio: ^5.3.2
  dio_smart_retry: ^5.0.0
  pretty_dio_logger: ^1.3.1

  image_picker: ^1.1.2
  file_picker: ^8.1.4
  open_filex: ^4.6.0
  path: ^1.9.0

  intl: ^0.19.0
  lottie: ^3.1.2
  url_launcher: ^6.3.1
  visibility_detector: ^0.4.0+2
  package_info_plus: ^8.1.1
  email_validator: ^3.0.0
  dotted_border: ^2.1.0
  flutter_native_splash: ^2.3.13
  like_button: ^2.0.5

  #media supporting
  better_player_plus: ^1.0.8

  easy_paymob: ^0.0.1
  fawaterk_payment: ^1.0.1

  timeago: ^3.7.0
  pretty_logger: ^1.0.0
  infinite_scroll_pagination: ^4.1.0
  shimmer: ^3.0.0
  salomon_bottom_bar: ^3.3.2
  flutter_expandable_fab: ^2.3.0
  wolt_modal_sheet: ^0.10.0
  dash_chat_2: ^0.0.21
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/splash/
    - assets/images/
    - assets/icons/
    - assets/images/illustration/
    - assets/logo/
    - assets/sound/
    - shorebird.yaml
