// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo6UraioZYTgAMHESKy2SvZefQUPe1Qns',
    appId: '1:139069549195:web:49b13d787934687ec0c28e',
    messagingSenderId: '139069549195',
    projectId: 'navy-d66c8',
    authDomain: 'navy-d66c8.firebaseapp.com',
    storageBucket: 'navy-d66c8.firebasestorage.app',
    measurementId: 'G-3LTBQM9BVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYqojMMhtxVfu927-s3UYHwNLkxy4Em0c',
    appId: '1:139069549195:android:144a9860d9d9df5cc0c28e',
    messagingSenderId: '139069549195',
    projectId: 'navy-d66c8',
    storageBucket: 'navy-d66c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACIgY1EqCNOuEyxFzO649CJ_HhCNzYPHQ',
    appId: '1:139069549195:ios:967eac826ea0168ec0c28e',
    messagingSenderId: '139069549195',
    projectId: 'navy-d66c8',
    storageBucket: 'navy-d66c8.firebasestorage.app',
    iosBundleId: 'com.osama.navy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo6UraioZYTgAMHESKy2SvZefQUPe1Qns',
    appId: '1:139069549195:web:51ebcd7224cc03abc0c28e',
    messagingSenderId: '139069549195',
    projectId: 'navy-d66c8',
    authDomain: 'navy-d66c8.firebaseapp.com',
    storageBucket: 'navy-d66c8.firebasestorage.app',
    measurementId: 'G-6Q113DVHS8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACIgY1EqCNOuEyxFzO649CJ_HhCNzYPHQ',
    appId: '1:139069549195:ios:24e7c55363c20e98c0c28e',
    messagingSenderId: '139069549195',
    projectId: 'navy-d66c8',
    storageBucket: 'navy-d66c8.firebasestorage.app',
    iosBundleId: 'com.example.navy',
  );

}